version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"


# Optionally declare the Python requirements required to build your docs
python:
  install:
  - requirements: docs/requirements.txt

formats:
  - pdf
  - epub